"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import {
  IndianRupee, CheckCircle2, Clock, FileDown, CreditCard, Loader2, AlertCircle,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { StatCard } from "@/components/dashboard/StatCard";
import { Payment } from "@/types";
import { formatCurrency, formatDate, getStatusColor, getStatusLabel } from "@/lib/utils";
import { createClient } from "@/lib/supabase/client";
import toast from "react-hot-toast";
import { useRouter } from "next/navigation";

interface Booking {
  id: string;
  total_amount: number;
  advance_amount: number;
  balance_amount: number;
  event_date: string;
  venue: string;
  city: string;
  status: string;
  enquiry?: { event_type: string } | null;
}

interface Props {
  bookings: Booking[];
  payments: Payment[];
}

export function ClientPaymentsClient({ bookings, payments: initialPayments }: Props) {
  const router = useRouter();
  const [payments, setPayments] = useState(initialPayments);
  const [payDialog, setPayDialog] = useState<{ booking: Booking; type: "advance" | "final" } | null>(null);
  const [transactionRef, setTransactionRef] = useState("");
  const [payAmount, setPayAmount] = useState("");
  const [marking, setMarking] = useState(false);

  const paidTotal = payments.filter((p) => p.status === "paid").reduce((s, p) => s + p.amount, 0);
  const pendingTotal = bookings.reduce((s, b) => s + b.balance_amount, 0);
  const totalBookings = bookings.reduce((s, b) => s + b.total_amount, 0);

  const openPayDialog = (booking: Booking, type: "advance" | "final") => {
    const amount = type === "advance" ? booking.advance_amount : booking.balance_amount;
    setPayAmount(String(amount));
    setTransactionRef("");
    setPayDialog({ booking, type });
  };

  const markAsPaid = async () => {
    if (!payDialog) return;
    if (!transactionRef.trim()) { toast.error("Please enter a transaction reference"); return; }
    setMarking(true);
    const supabase = createClient();
    const { data, error } = await supabase
      .from("payments")
      .insert({
        booking_id: payDialog.booking.id,
        type: payDialog.type,
        amount: Number(payAmount),
        status: "paid",
        notes: `Transaction Ref: ${transactionRef.trim()}`,
        paid_at: new Date().toISOString(),
      })
      .select()
      .single();
    if (error) {
      toast.error("Failed to record payment");
    } else {
      setPayments((prev) => [...prev, data as Payment]);
      toast.success("Payment recorded successfully!");
      setPayDialog(null);
      router.refresh();
    }
    setMarking(false);
  };

  const downloadInvoice = (booking: Booking) => {
    // Generate a simple text invoice and trigger download
    const bookingPayments = payments.filter((p) => p.booking_id === booking.id && p.status === "paid");
    const lines = [
      "BOOKMYEVENTSTAR — INVOICE",
      "=".repeat(40),
      `Event: ${booking.enquiry?.event_type ?? "Event"}`,
      `Date: ${formatDate(booking.event_date)}`,
      `Venue: ${booking.venue}, ${booking.city}`,
      "",
      `Total Amount:   ${formatCurrency(booking.total_amount)}`,
      `Advance Paid:   ${formatCurrency(booking.advance_amount)}`,
      `Balance Due:    ${formatCurrency(booking.balance_amount)}`,
      "",
      "Payment History:",
      ...bookingPayments.map((p) => `  ${p.type.toUpperCase()}: ${formatCurrency(p.amount)} — ${p.paid_at ? formatDate(p.paid_at) : "—"}`),
      "",
      "Generated by BookMyEventStar",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `invoice-${booking.id.slice(0, 8)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Invoice downloaded!");
  };

  return (
    <div className="p-4 md:p-6 space-y-6 max-w-4xl mx-auto">
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
        <StatCard title="Total Paid" value={formatCurrency(paidTotal)} icon={CheckCircle2} color="green" index={0} />
        <StatCard title="Balance Due" value={formatCurrency(pendingTotal)} icon={Clock} color="gold" index={1} />
        <StatCard title="Total Value" value={formatCurrency(totalBookings)} icon={IndianRupee} color="blue" index={2} />
      </div>

      <Card>
        <CardHeader><CardTitle>Event-wise Payment Summary</CardTitle></CardHeader>
        <CardContent className="space-y-4">
          {bookings.length === 0 ? (
            <div className="py-12 text-center text-muted-foreground text-sm">
              <IndianRupee className="w-10 h-10 mx-auto mb-3 opacity-20" />
              <p>No bookings yet. Your payments will appear here once a booking is confirmed.</p>
            </div>
          ) : (
            bookings.map((booking, i) => {
              const bookingPayments = payments.filter((p) => p.booking_id === booking.id);
              const advancePaid = bookingPayments.some((p) => p.type === "advance" && p.status === "paid");
              const finalPaid = bookingPayments.some((p) => p.type === "final" && p.status === "paid");
              const paidPct = booking.total_amount
                ? Math.round((booking.advance_amount / booking.total_amount) * 100)
                : 0;

              return (
                <motion.div
                  key={booking.id}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.08 }}
                  className="rounded-2xl border overflow-hidden"
                >
                  {/* Header */}
                  <div className="p-4 border-b bg-muted/20 flex items-center justify-between flex-wrap gap-3">
                    <div>
                      <p className="font-semibold text-sm">{booking.enquiry?.event_type ?? "Event"}</p>
                      <p className="text-xs text-muted-foreground">
                        {booking.venue} · {booking.city} · {formatDate(booking.event_date)}
                      </p>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className={`text-[10px] px-2 py-0.5 rounded-full ${getStatusColor(booking.status)}`}>
                        {getStatusLabel(booking.status)}
                      </span>
                      <Button size="sm" variant="outline" className="text-xs h-7 px-2" onClick={() => downloadInvoice(booking)}>
                        <FileDown className="w-3 h-3 mr-1" />Invoice
                      </Button>
                    </div>
                  </div>

                  {/* Amounts */}
                  <div className="p-4 grid grid-cols-3 gap-4 text-sm">
                    <div className="text-center p-3 rounded-xl bg-muted/30">
                      <p className="text-muted-foreground text-xs">Total</p>
                      <p className="font-bold mt-0.5">{formatCurrency(booking.total_amount)}</p>
                    </div>
                    <div className="text-center p-3 rounded-xl bg-emerald-50">
                      <p className="text-emerald-600 text-xs">Advance</p>
                      <p className="font-bold text-emerald-700 mt-0.5">{formatCurrency(booking.advance_amount)}</p>
                    </div>
                    <div className={`text-center p-3 rounded-xl ${booking.balance_amount > 0 ? "bg-amber-50" : "bg-emerald-50"}`}>
                      <p className={`text-xs ${booking.balance_amount > 0 ? "text-amber-600" : "text-emerald-600"}`}>Balance</p>
                      <p className={`font-bold mt-0.5 ${booking.balance_amount > 0 ? "text-amber-700" : "text-emerald-700"}`}>
                        {formatCurrency(booking.balance_amount)}
                      </p>
                    </div>
                  </div>

                  {/* Progress bar */}
                  <div className="px-4 pb-2">
                    <div className="h-2 bg-muted rounded-full overflow-hidden">
                      <div
                        className="h-full bg-gradient-to-r from-emerald-400 to-emerald-600 rounded-full transition-all"
                        style={{ width: `${paidPct}%` }}
                      />
                    </div>
                    <p className="text-xs text-muted-foreground mt-1">{paidPct}% paid</p>
                  </div>

                  {/* Payment action buttons */}
                  {["confirmed", "in_progress", "completed"].includes(booking.status) && (
                    <div className="px-4 pb-4 flex gap-2 flex-wrap">
                      {!advancePaid && (
                        <Button
                          size="sm"
                          variant="outline"
                          className="border-emerald-300 text-emerald-700 hover:bg-emerald-50"
                          onClick={() => openPayDialog(booking, "advance")}
                        >
                          <CreditCard className="w-3.5 h-3.5 mr-1.5" />
                          Pay Advance ({formatCurrency(booking.advance_amount)})
                        </Button>
                      )}
                      {advancePaid && !finalPaid && booking.balance_amount > 0 && (
                        <Button
                          size="sm"
                          variant="outline"
                          className="border-blue-300 text-blue-700 hover:bg-blue-50"
                          onClick={() => openPayDialog(booking, "final")}
                        >
                          <CreditCard className="w-3.5 h-3.5 mr-1.5" />
                          Pay Balance ({formatCurrency(booking.balance_amount)})
                        </Button>
                      )}
                      {advancePaid && finalPaid && (
                        <div className="flex items-center gap-1.5 text-emerald-600 text-sm font-medium">
                          <CheckCircle2 className="w-4 h-4" />Fully Paid
                        </div>
                      )}
                    </div>
                  )}

                  {/* Payment history */}
                  {bookingPayments.length > 0 && (
                    <div className="px-4 pb-4 space-y-1.5">
                      <p className="text-xs font-semibold text-muted-foreground uppercase mb-2">Payment History</p>
                      {bookingPayments.map((p) => (
                        <div key={p.id} className="flex items-center justify-between text-sm p-2 rounded-lg bg-muted/30">
                          <div className="flex items-center gap-2">
                            <span className={`w-2 h-2 rounded-full ${p.status === "paid" ? "bg-emerald-500" : "bg-amber-500"}`} />
                            <span className="capitalize">{p.type} payment</span>
                            {p.notes && <span className="text-xs text-muted-foreground">· {p.notes}</span>}
                          </div>
                          <div className="text-right">
                            <p className="font-medium">{formatCurrency(p.amount)}</p>
                            {p.paid_at && <p className="text-xs text-muted-foreground">{formatDate(p.paid_at)}</p>}
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </motion.div>
              );
            })
          )}
        </CardContent>
      </Card>

      {/* Pay Dialog */}
      <Dialog open={!!payDialog} onOpenChange={(o) => !o && setPayDialog(null)}>
        <DialogContent className="max-w-sm">
          <DialogHeader>
            <DialogTitle>Record Payment</DialogTitle>
          </DialogHeader>
          {payDialog && (
            <div className="space-y-4 mt-2">
              <div className="p-3 rounded-xl bg-muted/40 text-sm space-y-1">
                <p><span className="font-medium">Event:</span> {payDialog.booking.enquiry?.event_type}</p>
                <p><span className="font-medium">Type:</span> {payDialog.type === "advance" ? "Advance Payment" : "Final Balance Payment"}</p>
              </div>

              <div className="space-y-1.5">
                <Label>Amount (₹)</Label>
                <Input
                  type="number"
                  value={payAmount}
                  onChange={(e) => setPayAmount(e.target.value)}
                  className="font-semibold text-lg"
                />
              </div>

              <div className="space-y-1.5">
                <Label>Transaction Reference <span className="text-destructive">*</span></Label>
                <Input
                  placeholder="e.g. UPI Ref: 1234567890 or Cheque No."
                  value={transactionRef}
                  onChange={(e) => setTransactionRef(e.target.value)}
                />
                <p className="text-xs text-muted-foreground">Enter your UPI transaction ID, bank transfer ref, or cheque number.</p>
              </div>

              <div className="p-3 rounded-xl bg-amber-50 border border-amber-200 flex gap-2 text-sm text-amber-700">
                <AlertCircle className="w-4 h-4 flex-shrink-0 mt-0.5" />
                <p>This records your offline payment. Our coordinator will verify and confirm receipt.</p>
              </div>

              <div className="flex gap-3 justify-end">
                <Button variant="outline" onClick={() => setPayDialog(null)}>Cancel</Button>
                <Button onClick={markAsPaid} loading={marking}>
                  <CreditCard className="w-4 h-4 mr-2" />Confirm Payment
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
